### PR TITLE
Fix log formatting issue 132

### LINKED ISSUE #132: When prefix_logs="false" is set, % signs logged by the function are interpreted as fmt.Printf verbs
If you set the environment variable prefix_logs to false, % signs are interpreted by of-watchdog as fmt.Printf verbs.

## Expected Behaviour
% signs should not be interpreted

## Current Behaviour
If your function logs "%s", of-watchdog substitutes "%!s(MISSING)"

## Possible Solution

Don't use fmt.Printf() to log data from the function.

## Steps to Reproduce (for bugs)
1. Create a function that has ENV prefix_logs="false"
2. Deploy that function
3. Log "%s" from your function.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
20.10.13

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes 1.23.5

* Operating System and version (e.g. Linux, Windows, MacOS):
CentOS 7

* Link to your project or a code example to reproduce issue:

### PR DESCRIPTION
**Pull request by jcollie**
Signed-off-by: Jeffrey C. Ollie <jeff@ocjtech.us>

Fix #132

## Description
Don't pass the scanned text from the function as the format string to fmt.Printf.

## Motivation and Context
When not prefixing the output from the function, of-watchdog would pass the output as the format string to fmt.Printf. That would mean that anything that looked like a % verb would get misinterpreted.

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

File: executor/logging.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ func bindLoggingPipe(name string, pipe io.Reader, output io.Writer, logPrefix bo
 			if logPrefix {
 				logger.Printf("%s: %s", name, scanner.Text())
 			} else {
-				logger.Printf(scanner.Text())
+				logger.Printf("%s", scanner.Text())
```
Comment (LucasRoesler) [inline executor/logging.go:36]: I was expecting something like `logger.Print` so that there is no way to cause any formatting, but this works

**Review by LucasRoesler — COMMENTED** [review]
This look good, but can you fill in the "how has this been tested" section? 

I think the easiest way to test it is to build and publish an image from your branch. Then in your test function, just change the template Dockefile to reference your image instead of the official of-watchdog. Usually it is the top line, for example https://github.com/openfaas/golang-http-template/blob/eb793ff6f2749e1ebb02f4c235a78d7602102d7e/template/golang-http/Dockerfile#L1

**Review by LucasRoesler — APPROVED** [review]

**Comment by LucasRoesler** [comment]
@alexellis i have tried this out and :+1:

**Comment by alexellis** [comment]
Thanks @LucasRoesler, we should still have @jcollie fill out "How Has This Been Tested?" for the paper trail, for anyone landing here in the future.

A code sample for producing the error, and the before / after output.

Unless you have one and can share it below?

**Review by alexellis — APPROVED** [review]
Approved for merge. See comment.

**Comment by jcollie** [comment]
> Thanks @LucasRoesler, we should still have @jcollie fill out "How Has This Been Tested?" for the paper trail, for anyone landing here in the future.

Sorry it's taken a bit for me to get around to this but I the other day I did build a custom version of the watchdog with my patch and deployed it with a function.

**Comment by alexellis** [comment]
> How Has This Been Tested?

This has still been left blank. We're looking for console output here and / or code examples for the function.

Given that @LucasRoesler has tested this independently, I'll merge it, however we would still like the paperwork to be filled out. Unless I'm misunderstanding the change, it should not take more than a few minutes?

You can run the watchdog on your host without building a container or patching a template.

Alex

**Comment by alexellis** [comment]
The change is now available in [0.9.4](https://github.com/openfaas/of-watchdog/releases/tag/0.9.4)

Please feel free to send a PR to the template you were using @jcollie when you saw the problem, and update the Dockerfile for it. Unfortunately you didn't mention the template name in your issue, but you can find the repo via `faas-cli template store` commands.

Alex
